import Head from "next/head";
import { styled } from "styled-components";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <section>
          <h1>Home</h1>
        </section>
      </Main>
    </>
  );
}
const Main = styled.main`
  section {
  }
`;
